"""Added imdb related fields to movie

Revision ID: 3a34c37086ff
Revises: 3df142e5af8c
Create Date: 2025-12-29 02:16:47.563473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a34c37086ff'
down_revision = '3df142e5af8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_title', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('image_width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image_height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aggregateRating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('aggregateRating')
        batch_op.drop_column('image_height')
        batch_op.drop_column('image_width')
        batch_op.drop_column('image_url')
        batch_op.drop_column('primary_title')

    # ### end Alembic commands ###
