"""Added start year

Revision ID: 8487f6a81614
Revises: 3a34c37086ff
Create Date: 2025-12-29 02:19:13.261378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8487f6a81614'
down_revision = '3a34c37086ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregate_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_year', sa.Integer(), nullable=True))
        batch_op.drop_column('aggregateRating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregateRating', sa.FLOAT(), nullable=True))
        batch_op.drop_column('start_year')
        batch_op.drop_column('aggregate_rating')

    # ### end Alembic commands ###
